#!/bin/bash

EMAIL=${cert_email}
DOMAINS=(${cert_domains})

if [ -z "$DOMAINS" ]; then
  echo "ERROR: Domain list is empty or unset"
  exit 1
fi

if [ -z "$EMAIL" ]; then
  echo "ERROR: Email is empty string or unset"
  exit 1
fi

domain_args=""
for i in "${DOMAINS[@]}"
do
  domain_args="$domain_args -d $i"
done

if [ -n "${LETSENCRYPT_ENDPOINT+1}" ]; then
  echo "server = $LETSENCRYPT_ENDPOINT" >> /etc/letsencrypt/cli.ini
fi

letsencrypt certonly \
  --standalone \
  --standalone-supported-challenges http-01 \
  --text --renew-by-default --agree-tos \
  $domain_args \
  --email=$EMAIL

if [ -d /etc/letsencrypt/transfer/.git ]; then
  export GIT_COMMITTER_NAME="Letsencrypt"
  export GIT_COMMITTER_EMAIL="$cert_email"
  cd /etc/letsencrypt/transfer/
  cp --dereference --recursive --force /etc/letsencrypt/live/* .
  git add .
  git commit -m "$cert_domains $LETSENCRYPT_ENDPOINT" --author="Letsencrypt <$cert_email>"
  git push
fi

# TEMPORARY keep the container running for troubleshooting
sleep 3600
